### ISSUE TITLE
Develop a new version of the Code as Data / ML on Code diagram from the homepage

### ISSUE THREAD

**Issue by vcoisne** [src-d/design#20]
After a discussion with Jean we'd like to develop a v2 of this diagram https://sourced.tech/img/how_it_works.svg the 

Here are a couple suggestions: 

- Include source{d} lookout / assisted code review in the ML on Code side
- Include the name of the git platforms source{d} Engine can retrieve source code from i.e GitHub, GitLab, Bitbucket
- Include the name of the BI platforms for insights & dashboarding i.e PowerBI, Looker and Tableau
- Color Coding is good with green for code as data and orange for ML on code, but would be good to draw boundaries to explain what is the source{d} platform, and keep the violet out of the boundaries, as inputs and outputs

cc @campoy @marnovo @ricardobaeta

**Comment by marnovo** [comment]
@vcoisne yup, please add this to https://github.com/src-d/feature-idea/ so we can refine it a bit before working on it.

**Comment by vcoisne** [comment]
Thanks @marnovo - I opened a new issue there https://github.com/src-d/feature-idea/issues/120

**Comment by marnovo** [comment]
Thank you we'll move from there.
