### ISSUE TITLE
Larger sizes (more DPI) for logos on media kit

### ISSUE THREAD

**Issue by marnovo** [src-d/design#23]
Right now the largest size available for each raster variation is too small/low res for print and even hi-res screen usage.

**Comment by ricardobaeta** [comment]
@marnovo All logos on the [Media Kit](https://github.com/src-d/design/blob/master/media-kit/README.md) are already updated with the Illustrator exported images (72dpi / 150dpi / 300dpi) 

> Closing this per objective accomplishment.
