### ISSUE TITLE
Update assets with sharper Illustrator export

### ISSUE THREAD

**Issue by marnovo** [src-d/design#24]
Given we've found out the solution to getting sharper exports (a.k.a. using Illustrator directly), many assets like the logos and the business cards will need to be re-exported at sharp quality.

**Comment by ricardobaeta** [comment]
@marnovo all logos and main assets are already updated in this repo. Regarding the business cards, we have the Illustrator file, and we know how to export now. When the time comes to create business cards we will have proper quality assets to send to the printer.

> closing this per objective accomplishment.
