### ISSUE TITLE
Add source{d} diagram and product logos to assets

### ISSUE THREAD

**Issue by marnovo** [src-d/design#25]
Add [source{d} architecture diagram](https://github.com/src-d/backlog/issues/1385) and [Engine](https://github.com/src-d/product/issues/287)/[Lookout product logos](https://github.com/src-d/product/issues/297) to vector/raster assets.

- [x] [source{d} architecture diagram](https://github.com/src-d/design/blob/master/files/code-as-data-ml-on-code-diagram.png)
- [x] Engine Logo
- [x] Lookout Logo

**Comment by ricardobaeta** [comment]
Update: [source{d} architecture diagram](https://github.com/src-d/design/blob/master/files/code-as-data-ml-on-code-diagram.png) can already be found on this repo.

**Comment by ricardobaeta** [comment]
Update: source{d} Engine & Lookout Logos are already on the [Media Kit](https://github.com/src-d/design/blob/master/media-kit/README.md).

> closing this per objective accomplishment.
