### ISSUE TITLE
PNGs of Brackets square logo

### ISSUE THREAD

**Issue by marnovo** [src-d/design#4]
We need PNG versions of the Brackets square logo as we have for others:
https://github.com/src-d/artwork/blob/master/media-kit/README.md#brackets-version

**Comment by dpordomingo** [comment]
And I wonder if `favicon` should also be provided there

**Comment by ricardobaeta** [comment]
Here @dpordomingo https://docs.google.com/presentation/d/1q290ZrAMola1nSwzYmScOo3gsMgEIXKi2BsWgnMY078/edit#slide=id.g499db0cd7a_0_44

**Comment by ricardobaeta** [comment]
Closed per objective accomplishment.

> https://github.com/src-d/design/blob/master/media-kit/files/logo-brackets-x2.png
> https://github.com/src-d/design/blob/master/media-kit/files/logo-brackets-x4.png

**Comment by marnovo** [comment]
Reopening this as, even though the files exist, they're [not linked in the media kit file](https://github.com/src-d/design/blob/master/media-kit/README.md#brackets-version).

**Comment by ricardobaeta** [comment]
Thanks @marnovo ! Done :)
